### ISSUE TITLE
Haplotypes don't add to 100%

### ISSUE THREAD

**Issue by cvk1988** [vtsyvina/CliqueSNV#10]
Hello, 
Your tool is amazing and intuitive to use. I am, however, having an issue with the tool frequency outputs. On our data, cliques assembly reports 3 haplotypes and the respective frequencies do not add to 100%. The dataset is a mock community of known composition. What could be a reason for this?

![Screen Shot 2020-10-15 at 3 50 22 PM](https://user-images.githubusercontent.com/59971044/96193940-262e9080-0efe-11eb-93e6-aa156db3f243.png)

I appreciate your tool and your help!

**Comment by vtsyvina** [comment]
Hello,

We have a filtering step where all haplotypes with frequency less than -tf parameter is deleted from the output. You can read about it in the README.  By default a conservative strategy is chosen with 5% cutoff. You can lower this down to, let's say 1% but it is always a tradeoff when reading errors and other noise can get into results
