### ISSUE TITLE
Prevent -oe from exceeding the bounds of the haplotype

### ISSUE THREAD

**Issue by TheWhyofFry** [vtsyvina/CliqueSNV#11]
Hi there

If you provide the -oe option and this value exceed the length of the haplotype, an exception occurs.  I'm using CliqueSNV in a pipeline and sometimes it's difficult to detect whether the -os -oe values fall within the bounds of the haplotype. My knowledge of java is minimal and I've implemented a fix (but not in an elegant way) by using an intermediate "end" variable and constraining it to the length.  The solution works, but I fear a pull request would be ugly :-)

**Comment by vtsyvina** [comment]
Hello,

Thanks for letting me know about this bug. I just fixed it with the latest minor version. You can get the latest jar directly from the repo or google drive link.

When running it should show "1.5.6.1" version
