### ISSUE TITLE
[Suggestion] Change haplotype numbering to 1-based

### ISSUE THREAD

**Issue by maciejmotyka** [vtsyvina/CliqueSNV#2]
I know that for a Java programmer this might seem strange :wink:, but I have a hunch that majority of biologists and bioinformaticians are more familiar with 1-based numbering than 0-based.
Also, all of the other haplotype reconstruction programs use 1-based numbering, so when I'm comparing outputs I can't just say "Okay, let's now compare strain 2 from CliqueSNV with strain 2 from aBayesQR" unless I change the CliqueSNV output files first or remember to use strain 1 instead of 2.
Cheers!

**Comment by vtsyvina** [comment]
Thanks for the suggestion. Yes, I see how it may be more convenient, so I made this simple fix and you can use it.

Best,
Slava
