### ISSUE TITLE
Circular genomes

### ISSUE THREAD

**Issue by aponsero** [vtsyvina/CliqueSNV#6]
Hi all,

Thank you for this amazing tool! I was wondering if you have some recommendation to best use CliqueSNV with circular viral genomes. Any pitfall we need to avoid in this case?

Thank you for your help,

Alise

**Comment by vtsyvina** [comment]
Hello, Alise.

Sorry for the late reply. Unfortunately, circular genomes are out of scope for our tool. If only you can create some sam file that will make sense(not even sure how circular genomes are represented) then the tool can handle it and provide some meaningful results
