### ISSUE TITLE
suggested addon

### ISSUE THREAD

**Issue by antoine4ucsd** [vtsyvina/CliqueSNV#7]
amazing job!
one nice  improvement to the output would be to include the number of reads used for each haplotype and put it in the sequence name. is it something you can get ?
a summary table with statistics would also be cool (total reads , retained, Freq, etc)

congrats again. the algorithm gives me really interesting results so far.

**Comment by gallardo-seq** [comment]
I second @antoine4ucsd 's comment. Having a CSV file that lists the read names that were use to generate a particular clique would be a really useful feature. Maybe the program generating an intermediate file like this that is not retained? Great program, very user friendly and results are very accurate with our control datasets!

**Comment by vtsyvina** [comment]
Hello.

I implemented simple version of what you asked in the latest version. Use "-rn" option.
It will create the list with read names related to each haplotype. But note that the same read can go to different haplotypes (if they are on the same distance) or not go anywhere at all.
 
Also, for Illumina data the algorithm has pretty complex workflow with several stages when it aggregates the results with different thresholds, so it is not trivial to say what reads depends to what haplotypes. But still the tool will output read list as best as it can=)

For summary table I guess you never know what another person will need, but if you have specific suggestions I might try to implement them

**Comment by antoine4ucsd** [comment]
thank you so much! I will test it asap and let you know how it works for me. do you include the num_read in the seq name?

**Comment by antoine4ucsd** [comment]
Hello
still working with your algorithm. really interesting results so far. 
I can't find a way to set a minimum coverage . is it possible to set a min coverage AND a min frequency (and include the number of reads for each haplotype in the sequence name besides its frequency).
Also, cliqueSNV seems to freeze for some samples (probably due to memory issue and/or problematic samples). would you have any suggestions in such situation? I can share a sample in mp if you have time.

Best.

**Comment by vtsyvina** [comment]
Coverage doesn't make much sense here. We add reads to one or another haplotype based on SNPs. If some region is not covered by SNPs then reads from that region will be ignored because there is no evidence to decide from which haplotype they came from.

We have minimum support for SNPs parameter(-t) but it works locally for pair of correlated SNPs. 

You can send me the sample, I will have a look

**Comment by antoine4ucsd** [comment]
Thank you! Can you give me a mp and I will send you a link
Best

--
a

**Comment by vtsyvina** [comment]
mp? Not sure what is it

**Comment by antoine4ucsd** [comment]
Sorry I meant email

--
a

**Comment by vtsyvina** [comment]
v.tsyvina@gmail.com
